spring.application.name=Machine
spring.datasource.url=jdbc:postgresql://localhost:5432/dummybase
spring.datasource.username=postgres
spring.datasource.password=sql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true